language: php

php:
    - 5.3
    - 5.4
    - 5.5

matrix:
    allow_failures:
        - php: 5.5

before_script:
    pecl install channel://pecl.php.net/libevent-0.0.5
    config-add php-libevent.ini
